### ISSUE TITLE
Hey Tantan, I followed your tutorial to make the game in Crystal. Thank you! \o

### ISSUE THREAD

**Issue by rubynho** [TanTanDev/rusty_pong#1]
I'm just getting started with game development and the Crystal programming language in my spare time so the code is a bit messy.

Nice to have people like you to get inspired and try new things.

Here is the [source code](https://github.com/rubynho/crystal_pong) in case you want to check it out. :)

**Comment by Ponot** [comment]
> I'm just getting started with game development and the Crystal programming language in my spare time so the code is a bit messy.
> 
> Nice to have people like you to get inspired and try new things.
> 
> Here is the [source code](https://github.com/rubynho/crystal_pong) in case you want to check it out. :)

This is not a issue!
